job('petclinic-service') {
    description("Simple jenkins job generated by the DSL on ${new Date()}, the project is a small maven project hosted on github")
    label('master')
    logRotator {
        numToKeep 20
    }
    scm {
        git {
            remote {
                github('hamid2013/spring-petclinic', 'https')
            }
            branch('master')
        }
    }
    steps {
        shell('./mvnw spring-boot:run')
    }
    publishers {
        archiveArtifacts 'build/libs/*.war'
        archiveJunit 'build/test-results/**/*.xml'
    }
}
